name: 'CLI Git Actions'
description: 'Get the time in the specified time zone'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  timeZone:
    description: 'time zone'
    required: false
    default: 0
  format:
    description: 'timestamp format'
    required: false
    default: ''
  string:
    description: The input string
    required: false
    default: ''
  urls:
    description: 'List of URL(s) to analyze'
  budgetPath:
      description: 'Path to a Lighthouse budgets.json file'
  configPath:
    description: 'Path to a LHCI lighthouserc.json file'
  uploadArtifacts:
    description: 'Opt-out of saving Lighthouse results as an action artifacts'
  artifactName:
    description: 'Name of the artifact group if using uploadArtifacts. default: lighthouse-results'
    default: 'lighthouse-results'
  runs:
    description: 'Number of runs to do per URL'
  serverBaseUrl:
    description: 'Address of a LHCI server'
  serverToken:
    description: 'API token to push to LHCI server'
  basicAuthUsername:
    description: 'Basic auth username for LHCI server'
  basicAuthPassword:
    description: 'Basic auth password for LHCI server'
outputs:
  time:
    description: 'current time'
  lowercase:
    description: The input string, with any uppercase characters replaced with lowercase ones
  uppercase:
    description: The input string, with any lowercase characters replaced with uppercase ones
  capitalized:
    description: The input string, with any alphabetical characters lowercase, except for the first character, which is uppercased
  resultsPath:
    description: 'Path to the folder with LHCI results'
  links:
    description: 'Links to compare/result UI for each URL (content of links.json)'
  assertionResults:
    description: 'Assertion results (content of assertion-results.json)'
runs:
  using: 'node16'
  main: 'dist/index.js'