name: 'CLI Git Actions'
description: 'Get the time in the specified time zone'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  timeZone:
    description: 'time zone'
    required: false
    default: 0
  format:
    description: 'timestamp format'
    required: false
    default: ''
  string:
    description: The input string
    required: false
    default: ''  
outputs:
  time:
    description: 'current time'
  lowercase:
    description: The input string, with any uppercase characters replaced with lowercase ones
  uppercase:
    description: The input string, with any lowercase characters replaced with uppercase ones
  capitalized:
    description: The input string, with any alphabetical characters lowercase, except for the first character, which is uppercased  
runs:
  using: 'node16'
  main: 'dist/index.js'