name: test-action-Lighthouse
on:
  push:
    branches:
      - test-action-light
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://www.seat.de
          uploadArtifacts: true # save results as an action artifacts