name: test-action-Lighthouse
on:
  push:
    branches:
      - test-action
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: ./
        with:
          urls: |
            https://example.com/
            https://example.com/blog
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: false # upload lighthouse report to the temporary storage